### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by minibhati93** [minibhati93/programming-problems#1]
- [ ] Create a new file CONTRIBUTING.md
- [ ] Move the contributing section from README.md to this file
- [ ] Add a note in README referring to CONTRIBUTING.md

**Comment by vidhan13j07** [comment]
@minibhati93, I want to take up this issue.

**Comment by minibhati93** [comment]
Apologies @vidhan13j07 . Already received a pull request. Thanks anyway 👍
