### ISSUE TITLE
Plus Minus problem

### ISSUE THREAD

**Issue by minibhati93** [minibhati93/programming-problems#5]
HackerRank Problem:
Given an array of integers, calculate which fraction of its elements are positive, which fraction of its elements are negative, and which fraction of its elements are zeroes, respectively. Print the decimal value of each fraction on a new line.

The detailed problem statement is in this readme [https://github.com/minibhati93/programming-problems/blob/master/algorithms/hackerrank-problems/PlusMinus/README.md](Problem statement)

This is to be implemented in Python 2.7

**Comment by mayanksatnalika** [comment]
I have opened a pr for  the implementation in python 2.7

**Comment by minibhati93** [comment]
#8
